
# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala
scala:
   - 2.11.4
branches:
  only:
    - master
script:
  - "sbt clean coverage test coveralls coverageReport coverageAggregate codacyCoverage"
after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && sbt stage deployHeroku || false'
