
# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala
scala:
   - 2.11.4
branches:
  only:
    - master
script: "sbt clean coverage test"
after_success:
  - "sbt coveralls"
  - "sbt coverageReport"
  - "sbt coverageAggregate"
  - "sbt codacyCoverage"
